# Generated by Django 4.2.5 on 2023-09-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lib", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="t_url",
            name="url",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
    ]
