# Generated by Django 4.2.5 on 2023-11-04 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0048_alter_lecturer_employee_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(default='Diploma', max_length=255)),
                ('description', models.TextField()),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Foundation', max_length=255)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.program')),
            ],
        ),
        migrations.CreateModel(
            name='Fees_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Cash', 'Cash'), ('Transfer', 'Transfer'), ('Other', 'Other')], max_length=50)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owing', models.DecimalField(decimal_places=2, max_digits=8)),
                ('semester', models.CharField(choices=[('year one', 'Year One'), ('year two', 'Year Two'), ('year three', 'Year Three'), ('year four', 'Year Four'), ('diploma one', 'Diploma One'), ('diploma two', 'Diploma Two'), ('certificate', 'Certificate')], max_length=20)),
                ('fee_type', models.CharField(choices=[('fees', 'Fees'), ('levy', 'Levy')], max_length=10)),
                ('is_fully_paid', models.BooleanField(default=False)),
                ('date_paid', models.DateField()),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.enrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.programlevel'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.program'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
    ]
