# Generated by Django 4.2.5 on 2023-09-19 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0004_rename_studentclass_studentclasse'),
        ('accounts', '0019_alter_lecturer_employee_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_title', models.CharField(max_length=250)),
                ('assignment_description', models.TextField(max_length=200)),
                ('assignment_file', models.FileField(upload_to='assignment_submissions')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.student')),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.studentclasse')),
            ],
        ),
    ]
