# Generated by Django 4.2.5 on 2023-09-19 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_assignment_assignmentsubmission_course_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notify_class',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
