# Generated by Django 4.2.5 on 2023-10-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_alter_studentclass_student_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentclass",
            name="student_class",
            field=models.CharField(default="HIM-LEC-01", max_length=50),
        ),
    ]
