# Generated by Django 3.2.22 on 2023-11-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_studentclass_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='student_class',
            field=models.CharField(default='', max_length=50),
        ),
    ]
