# Generated by Django 4.2.5 on 2023-09-10 07:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_lecturer_employee_number_and_more'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='class',
            name='max_students',
        ),
        migrations.RemoveField(
            model_name='class',
            name='schedule',
        ),
        migrations.AddField(
            model_name='class',
            name='class_code',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='class_name',
            field=models.CharField(default='class', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.lecturer'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_type',
            field=models.CharField(choices=[('online', 'Online'), ('physical', 'Physical')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='material_downloads',
            field=models.FileField(blank=True, null=True, upload_to='class_materials/'),
        ),
        migrations.AddField(
            model_name='class',
            name='online_platform',
            field=models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('google_meet', 'Google Meet'), ('webex', 'Cisco Webex'), ('skype', 'Skype')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='online_platform_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
