# Generated by Django 4.2.5 on 2023-09-10 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_lecturer_employee_number_and_more'),
        ('courses', '0001_initial'),
        ('classes', '0002_remove_class_lecturer_remove_class_max_students_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='StudentClass',
        ),
    ]
