# Generated by Django 4.2.5 on 2023-09-10 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_lecturer_employee_number_and_more'),
        ('courses', '0001_initial'),
        ('classes', '0003_rename_class_studentclass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentClass',
            new_name='StudentClasse',
        ),
    ]
