# Generated by Django 4.2.5 on 2023-09-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_choice_question_studentresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclasse',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasse',
            name='meeting_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentclasse',
            name='meeting_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
