# Generated by Django 4.2.5 on 2023-09-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_studentclasse_meeting_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclasse',
            name='meeting_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentclasse',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
