# Generated by Django 4.2.5 on 2023-09-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_studentclasse_meeting_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentclasse',
            old_name='meeting_date',
            new_name='lesson_date',
        ),
        migrations.RenameField(
            model_name='studentclasse',
            old_name='meeting_description',
            new_name='lesson_description',
        ),
        migrations.RenameField(
            model_name='studentclasse',
            old_name='meeting_time',
            new_name='lesson_end_time',
        ),
        migrations.RenameField(
            model_name='studentclasse',
            old_name='meeting_title',
            new_name='lesson_title',
        ),
        migrations.RemoveField(
            model_name='studentclasse',
            name='description',
        ),
        migrations.RemoveField(
            model_name='studentclasse',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='studentclasse',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='studentclasse',
            name='online_platform',
        ),
        migrations.RemoveField(
            model_name='studentclasse',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='studentclasse',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='studentclasse',
            name='start_time',
        ),
        migrations.AddField(
            model_name='studentclasse',
            name='lesson_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
