# Generated by Django 4.2.5 on 2023-09-26 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('accounts', '0032_alter_lecturer_employee_number_and_more'),
        ('classes', '0008_rename_meeting_date_studentclasse_lesson_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclasse',
            name='class_teacher',
        ),
        migrations.RemoveField(
            model_name='studentclasse',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='studentclasse',
            name='lesson_date',
        ),
        migrations.RemoveField(
            model_name='studentclasse',
            name='lesson_description',
        ),
        migrations.RemoveField(
            model_name='studentclasse',
            name='lesson_end_time',
        ),
        migrations.RemoveField(
            model_name='studentclasse',
            name='lesson_start_time',
        ),
        migrations.RemoveField(
            model_name='studentclasse',
            name='lesson_title',
        ),
        migrations.RemoveField(
            model_name='studentclasse',
            name='material_downloads',
        ),
        migrations.RemoveField(
            model_name='studentclasse',
            name='online_platform_link',
        ),
        migrations.CreateModel(
            name='OnlineLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_title', models.CharField(blank=True, max_length=255, null=True)),
                ('lesson_description', models.TextField(blank=True, max_length=255, null=True)),
                ('lesson_date', models.DateField(blank=True, null=True)),
                ('lesson_start_time', models.TimeField(blank=True, null=True)),
                ('lesson_end_time', models.TimeField(blank=True, null=True)),
                ('material_downloads', models.FileField(blank=True, null=True, upload_to='class_materials/')),
                ('online_platform_link', models.URLField(blank=True, null=True)),
                ('course_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='OfflineLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(blank=True, max_length=255, null=True)),
                ('lesson_description', models.TextField(blank=True, max_length=255, null=True)),
                ('lesson_date', models.DateField(blank=True, null=True)),
                ('lesson_start_time', models.TimeField(blank=True, null=True)),
                ('lesson_end_time', models.TimeField(blank=True, null=True)),
                ('material_downloads', models.FileField(blank=True, null=True, upload_to='class_materials/')),
                ('course_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.lecturer')),
            ],
        ),
    ]
