# Generated by Django 4.2.5 on 2023-11-04 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_alter_lecturer_employee_number_and_more'),
        ('courses', '0002_remove_course_max_students_and_more'),
        ('classes', '0009_remove_studentclasse_class_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinelesson',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.studentclasse'),
        ),
        migrations.AddField(
            model_name='offlinelesson',
            name='students',
            field=models.ManyToManyField(to='accounts.student'),
        ),
        migrations.AddField(
            model_name='onlinelesson',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.studentclasse'),
        ),
        migrations.AddField(
            model_name='onlinelesson',
            name='students',
            field=models.ManyToManyField(to='accounts.student'),
        ),
        migrations.AddField(
            model_name='studentclasse',
            name='courses',
            field=models.ManyToManyField(to='courses.course'),
        ),
    ]
