# Generated by Django 4.2.5 on 2023-10-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0010_lessonallocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onlinelesson",
            name="course_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
