# Generated by Django 4.2.5 on 2023-10-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0013_alter_onlinelesson_lecturer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessonallocation",
            name="student",
        ),
    ]
