# Generated by Django 4.2.5 on 2023-10-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0014_remove_lessonallocation_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonallocation",
            name="lecturer",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
