# Generated by Django 4.2.5 on 2023-10-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0015_lessonallocation_lecturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonallocation",
            name="status",
            field=models.CharField(default="Inactive", max_length=20),
        ),
    ]
