# Generated by Django 4.2.5 on 2023-10-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classes",
            fields=[
                ("class_id", models.AutoField(primary_key=True, serialize=False)),
                ("class_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                ("lecturer_id", models.AutoField(primary_key=True, serialize=False)),
                ("lecturer_name", models.CharField(max_length=255)),
                ("other_details", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ProgramLevel",
            fields=[
                ("level_id", models.AutoField(primary_key=True, serialize=False)),
                ("level_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                ("student_id", models.AutoField(primary_key=True, serialize=False)),
                ("student_name", models.CharField(max_length=255)),
                ("other_details", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="StudentClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_linked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program.classes",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program.students",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("program_id", models.AutoField(primary_key=True, serialize=False)),
                ("program_name", models.CharField(max_length=255)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program.programlevel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("lesson_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "class_linked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program.classes",
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program.lecturer",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program.students",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Courses",
            fields=[
                ("course_id", models.AutoField(primary_key=True, serialize=False)),
                ("course_name", models.CharField(max_length=255)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program.programlevel",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program.program",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="classes",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="program.courses"
            ),
        ),
        migrations.AddField(
            model_name="classes",
            name="lecturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="program.lecturer"
            ),
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("assignment_id", models.AutoField(primary_key=True, serialize=False)),
                ("assignment_name", models.CharField(max_length=255)),
                (
                    "class_linked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program.classes",
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program.lecturer",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program.students",
                    ),
                ),
            ],
        ),
    ]
