# Generated by Django 4.2.5 on 2023-10-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="student_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
