# Generated by Django 4.2.5 on 2023-09-10 06:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attendance_records',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='employee_number',
            field=models.CharField(default='HIM-LEC-362526', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='HIM-60558488-2023', max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'date')},
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='present',
        ),
    ]
