# Generated by Django 4.2.5 on 2023-09-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_lecturer_employee_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partnership_badge',
            field=models.CharField(choices=[('starter', 'Starter'), ('silver', 'Silver'), ('gold', 'Gold'), ('diamond', 'Diamond')], default='starter', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='employee_number',
            field=models.CharField(default='HIM-LEC-353989', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='HIM-22212907-2023', max_length=25),
        ),
    ]
