# Generated by Django 4.2.5 on 2023-09-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_partner_partnership_badge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='is_recurring',
            new_name='is_partnership_recurring',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='partnership_date',
            new_name='partner_joined_date',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='food_items',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='physical_items',
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='employee_number',
            field=models.CharField(default='HIM-LEC-663625', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='HIM-62266707-2023', max_length=25),
        ),
    ]
