<<<<<<< HEAD
# Generated by Django 4.2.5 on 2023-09-27 18:28
=======
# Generated by Django 4.2.5 on 2023-09-26 18:26
>>>>>>> 58415fefc043f9910e7093295c22ffd9c7e30004

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('accounts', '0027_alter_customuser_country_and_more'),
=======
        ("accounts", "0027_alter_customuser_country_and_more"),
>>>>>>> 58415fefc043f9910e7093295c22ffd9c7e30004
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('lecturer', 'Lecturer'), ('student', 'Student'), ('alumni', 'Alumni'), ('partner', 'Partner')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='employee_number',
            field=models.CharField(default='HIM-LEC-226655', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='HIM-20646441-2023', max_length=25),
=======
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("lecturer", "Lecturer"),
                    ("student", "Student"),
                    ("alumni", "Alumni"),
                    ("partner", "Partner"),
                ],
                default="student",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="employee_number",
            field=models.CharField(
                default="HIM-LEC-325145", max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(default="HIM-29229959-2023", max_length=25),
>>>>>>> 58415fefc043f9910e7093295c22ffd9c7e30004
        ),
    ]
