# Generated by Django 4.2.5 on 2023-10-03 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_lecturer_employee_number_and_more'),
        ('accounts', '0034_alter_lecturer_employee_number_and_more'),
    ]

    operations = [
    ]
