# Generated by Django 4.2.5 on 2023-10-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0045_alter_lecturer_employee_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="address",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="church_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="city",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="country",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="nationality",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="photo",
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="employee_number",
            field=models.CharField(
                default="HIM-LEC-656541", max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(default="HIM-51909852-2023", max_length=25),
        ),
    ]
