# Generated by Django 4.2.5 on 2023-10-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0049_remove_customuser_photo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="phone",
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="employee_number",
            field=models.CharField(
                default="HIM-LEC-441394", max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(default="HIM-67792202-2023", max_length=25),
        ),
    ]
