# Generated by Django 4.2.5 on 2023-10-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0051_remove_customuser_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userattributes",
            name="country",
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="employee_number",
            field=models.CharField(
                default="HIM-LEC-471486", max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(default="HIM-24090878-2023", max_length=25),
        ),
    ]
