# Generated by Django 4.2.5 on 2023-10-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0055_alter_lecturer_employee_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userattributes",
            name="root",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="employee_number",
            field=models.CharField(
                default="HIM-LEC-628559", max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(default="HIM-80990724-2023", max_length=25),
        ),
    ]
