# Generated by Django 4.2.5 on 2023-10-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0056_userattributes_root_alter_lecturer_employee_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="root",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="employee_number",
            field=models.CharField(
                default="HIM-LEC-404350", max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(default="HIM-76067243-2023", max_length=25),
        ),
    ]
