# Generated by Django 4.2.5 on 2023-10-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0066_remove_student_address_remove_student_phone_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.CharField(
                blank=True, default="Pending", max_length=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="employee_number",
            field=models.CharField(
                default="HIM-LEC-780346", max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(default="HIM-69017889-2023", max_length=25),
        ),
    ]
