# Generated by Django 4.2.5 on 2023-10-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0080_alter_lecturer_employee_number_alter_lecturer_gender_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturer",
            name="employee_number",
            field=models.CharField(
                default="HIM-LEC-551113", max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(default="HIM-53474836-2023", max_length=25),
        ),
    ]
