# Generated by Django 4.2.5 on 2023-10-16 23:51

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0087_alter_lecturer_employee_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userattributes",
            name="country",
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="employee_number",
            field=models.CharField(
                default="HIM-LEC-523111", max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(default="HIM-72076424-2023", max_length=25),
        ),
        migrations.AlterField(
            model_name="userattributes",
            name="className",
            field=models.CharField(default="", max_length=50),
        ),
    ]
