# Generated by Django 4.2.5 on 2023-09-10 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('course_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_students', models.PositiveIntegerField()),
                ('credits', models.PositiveIntegerField()),
                ('course_unit', models.CharField(max_length=200)),
                ('current_class', models.CharField(blank=True, choices=[('first_year', 'first_year'), ('second_year', 'second_year'), ('third_year', 'third_year'), ('certificate', 'certificate'), ('diploma_one', 'diploma_one'), ('diploma_two', 'diploma_two')], max_length=30)),
                ('semester', models.CharField(choices=[('First', 'First'), ('Second', 'Second')], max_length=20)),
                ('is_elective', models.BooleanField(blank=True, default=False, null=True)),
                ('location', models.CharField(choices=[('online', 'Online'), ('institute', 'Institute'), ('hybrid', 'Hybrid')], max_length=25)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('lecturer', models.ForeignKey(db_column='user.last_name', on_delete=django.db.models.deletion.CASCADE, to='accounts.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=200, unique=True)),
                ('is_current_session', models.BooleanField(blank=True, default=False, null=True)),
                ('next_session_begins', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TakenCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('exam', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1)),
                ('comment', models.CharField(blank=True, choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_courses', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], max_length=20)),
                ('semester', models.CharField(choices=[('First', 'First'), ('Second', 'Second')], max_length=100)),
                ('session', models.CharField(blank=True, max_length=100, null=True)),
                ('current_class', models.CharField(choices=[('first_year', 'first_year'), ('second_year', 'second_year'), ('third_year', 'third_year'), ('certificate', 'certificate'), ('diploma_one', 'diploma_one'), ('diploma_two', 'diploma_two')], max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='RepeatingStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_class', models.CharField(choices=[('first_year', 'first_year'), ('second_year', 'second_year'), ('third_year', 'third_year'), ('certificate', 'certificate'), ('diploma_one', 'diploma_one'), ('diploma_two', 'diploma_two')], max_length=100)),
                ('session', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(related_name='allocated_course', to='courses.course')),
                ('lecturer', models.ForeignKey(db_column='last_name', on_delete=django.db.models.deletion.CASCADE, to='accounts.lecturer')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.session')),
            ],
        ),
        migrations.CreateModel(
            name='CarryOverStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, choices=[('First', 'First'), ('Second', 'Second')], max_length=100, null=True)),
                ('current_class', models.CharField(blank=True, choices=[('first_year', 'first_year'), ('second_year', 'second_year'), ('third_year', 'third_year'), ('certificate', 'certificate'), ('diploma_one', 'diploma_one'), ('diploma_two', 'diploma_two')], max_length=30, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
