# Generated by Django 4.2.5 on 2023-11-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_alter_lecturer_employee_number_and_more'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='max_students',
        ),
        migrations.RemoveField(
            model_name='takencourse',
            name='student',
        ),
        migrations.AddField(
            model_name='takencourse',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='accounts.student'),
        ),
    ]
