# Generated by Django 4.2.5 on 2023-11-04 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_remove_studentclasse_class_teacher_and_more'),
        ('accounts', '0051_alter_lecturer_employee_number_and_more'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='student_class',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.studentclasse'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='students',
            field=models.ManyToManyField(related_name='assignments', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assigned_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_assigned_classes', to='classes.studentclasse'),
        ),
    ]
