# Generated by Django 4.2.5 on 2023-09-10 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('utilities', 'Utilities'), ('maintenance', 'Maintenance'), ('supplies', 'Supplies'), ('rent', 'Rent'), ('other', 'Other')], max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('money', 'Money'), ('food', 'Food'), ('items', 'Physical Items')], max_length=10)),
                ('purpose', models.CharField(max_length=100)),
                ('partnership_date', models.DateField()),
                ('partnered_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('food_items', models.TextField(blank=True, null=True)),
                ('physical_items', models.TextField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('fees', 'Fees'), ('levy', 'Levy')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('semester', models.CharField(choices=[('year one', 'Year One'), ('year two', 'Year Two'), ('year three', 'Year Three'), ('year four', 'Year Four'), ('diploma one', 'Diploma One'), ('diploma two', 'Diploma Two'), ('certificate', 'Certificate')], max_length=20)),
                ('is_fully_paid', models.BooleanField(default=False)),
                ('owing', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer')], max_length=50)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
