# Generated by Django 4.2.5 on 2023-09-10 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_lecturer_employee_number_and_more'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.lecturer'),
        ),
        migrations.AddField(
            model_name='fee',
            name='payment_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.lecturer'),
        ),
    ]
