# Generated by Django 4.2.5 on 2023-09-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_expense_payed_by_fee_payment_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer')], max_length=50, null=True),
        ),
    ]
