# Generated by Django 4.2.5 on 2023-11-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_expense_payment_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fee',
        ),
    ]
