# Generated by Django 4.2.5 on 2023-09-19 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_rename_studentclass_studentclasse'),
        ('lecturers', '0002_assignment_assigned_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='AssignmentNotification',
        ),
    ]
