# Generated by Django 4.2.5 on 2023-10-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecturers", "0003_rename_notification_assignmentnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentnotification",
            name="notification_rating",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
