# Generated by Django 4.2.5 on 2023-10-03 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("lecturers", "0004_assignmentnotification_notification_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentnotification",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assignmentnotification",
            name="notification_rating",
            field=models.CharField(
                choices=[
                    ("bg-skyblue", "Skyblue"),
                    ("bg-yellow", "Yellow"),
                    ("bg-pink", "Pink"),
                ],
                max_length=20,
            ),
        ),
    ]
