# Generated by Django 4.2.5 on 2023-10-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecturers", "0007_alter_assignmentnotification_assignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentnotification",
            name="notify_class",
            field=models.CharField(default="HIM-LEC-01", max_length=20),
        ),
    ]
